Pokemons
ki3kia/snake pull request #2
Opened 2022-06-08 13:39 UTC by ki3kia

2022-06-08 14:06 UTC, TheForsakenSpirit requested changes

2022-06-08 14:06 UTC, TheForsakenSpirit commented on src/PokemonList.tsx
> +    results: [],
try to fetch new page without previous data

2022-06-08 17:33 UTC, mrlika requested changes

2022-06-08 17:33 UTC, mrlika commented on src/App.css
> +    text-align: center;
All the CSS files should be formatted with Prettier

2022-06-09 13:17 UTC, mrlika requested changes

2022-06-09 13:17 UTC, mrlika commented on src/PokemonList.tsx
> +  return false;
Simplify
```suggestion
  return 'name' in (arg as Pokemon) && 'url' in (arg as Pokemon);
```

2022-06-09 13:17 UTC, mrlika commented on src/PokemonList.tsx
> +              key + 1
`pokemon.id` should be used here. not index.

2022-06-09 13:37 UTC, TheForsakenSpirit requested changes

2022-06-10 09:13 UTC, TheForsakenSpirit requested changes

2022-06-10 09:13 UTC, TheForsakenSpirit commented on src/PokemonList.tsx
> +  const PAGE_SIZE = 10;
```suggestion
  
const PAGE_SIZE = 10;

export const PokemonList = (): JSX.Element => {
  const section = useRef<HTMLElement>(null);
```

2022-06-13 11:31 UTC, TheForsakenSpirit requested changes

2022-06-13 11:31 UTC, TheForsakenSpirit commented on src/PokemonList.tsx
> +        }
Convert to `map` cycle.

2022-06-14 06:55 UTC, TheForsakenSpirit approved these changes

2022-06-14 07:07 UTC, mrlika approved these changes

2022-06-14 07:07 UTC, merged