snakeStyles
ki3kia/snake pull request #4
Opened 2022-06-16 13:18 UTC by ki3kia

2022-06-16 14:47 UTC, TheForsakenSpirit requested changes

2022-06-16 14:47 UTC, TheForsakenSpirit commented on src/App.tsx
> +      {isOnGame ? <SnakeStates pokemonId={pokemon} /> : <></>}
```suggestion
      {isOnGame ? <SnakeStates pokemonId={pokemon} /> : null}
```

2022-06-16 14:47 UTC, TheForsakenSpirit commented on src/Snake.tsx
> +  });
Is ```forEach``` required here?

2022-06-16 15:04 UTC, mrlika commented on src/Snake.tsx
> +  const elementStyles = (element: Point) => {
1) function name should start from a verb
2) this function doesn't use render function context and should be moved outside to global scope to avoid creating unnecessary closure with each render

getElementPositionStyle

2022-06-16 15:06 UTC, TheForsakenSpirit requested changes

2022-06-16 15:06 UTC, TheForsakenSpirit commented on src/Snake.tsx
> +const isSnakeBody = (snake: Point[], point: Point) => {
```suggestion
const isPointOutOfSnake = (snake: Point[], point: Point) => {
```

2022-06-17 13:07 UTC, mrlika approved these changes

2022-06-17 13:21 UTC, TheForsakenSpirit approved these changes

2022-06-17 13:37 UTC, merged