Camera controller
ki3kia/snake pull request #8
Opened 2022-06-29 08:27 UTC by ki3kia

2022-06-29 13:41 UTC, TheForsakenSpirit commented on src/gameUtils.ts
> +  }
Convert Math operation to constant values.

2022-06-29 18:51 UTC, mrlika requested changes

2022-06-29 18:51 UTC, mrlika commented on src/Camera.tsx
> +  }, [mediaStream]);
Break into 2 useEffects. One responsible for creating media stream. It should have no dependencies.
Another for using media stream - assigning to videoRef and stoping. Should depend on [mediaStream]

2022-06-29 18:51 UTC, mrlika commented on src/Snake.tsx
> +        id={'isCameraControl'}
Please configure your editor to not add unnecessary curly brackets

2022-06-30 08:31 UTC, mrlika requested changes

2022-06-30 08:31 UTC, mrlika commented on src/Camera.tsx
> +  });
```suggestion
    initCamera();
  }, []);
```

2022-06-30 08:31 UTC, mrlika commented on src/App.tsx
> +  const onCameraControl = (direction: Point) => {
We usually name it like
```suggestion
  const handleCameraDirection = (direction: Point) => {
```

2022-06-30 08:31 UTC, mrlika commented on src/Camera.tsx
> +const detectorPromise = handPoseDetection.createDetector(model, detectorConfig);
Each component should have its own detector e.g. to play two games on a single page simultaneously.

2022-06-30 08:42 UTC, ki3kia commented on src/Camera.tsx
> +const detectorPromise = handPoseDetection.createDetector(model, detectorConfig);
Placing a detector in a component will abort the detector

2022-06-30 13:03 UTC, TheForsakenSpirit requested changes

2022-06-30 13:03 UTC, TheForsakenSpirit commented on src/App.tsx
> +          onChange={() => setIsUseCamera((prev) => !prev)}
No need to use updater here. Just `setIsUseCamera(!isUseCamera)`

2022-06-30 13:03 UTC, TheForsakenSpirit commented on src/Snake.tsx
> +  }, [isPaused, cameraDirection]);
```suggestion
  directionRef.current = cameraDirection;
```

2022-06-30 15:00 UTC, mrlika requested changes

2022-07-02 08:22 UTC, mrlika requested changes

2022-07-02 08:22 UTC, mrlika commented on src/Camera.tsx
> +      if (direction) onChangeDirectionRef.current(direction);
Please add code to prevent execution of the 2 `detector.estimateHands` simultaneously on slow devices.

2022-07-04 07:47 UTC, mrlika commented on src/Camera.tsx
> +      if (hands) setTimeout(getDirection, DELAY);
1. Why AI loop should be stopped if there are no hands?
2. Use closure scope to save `timeoutId` and clear it in the cleanup.

2022-07-04 10:30 UTC, mrlika approved these changes

2022-07-05 07:22 UTC, TheForsakenSpirit approved these changes

2022-07-05 07:22 UTC, merged